# Generated by Django 4.1.7 on 2023-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_student_alter_uploadedimage_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3),
        ),
    ]
