# Generated by Django 4.1.7 on 2023-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_uploadedimage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='register_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
