# Generated by Django 4.1.7 on 2023-08-15 12:52

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_uploadedimage_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=pages.models.UploadedImage.image_upload_path),
        ),
    ]
