# Generated by Django 4.2.4 on 2023-08-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_uploadedimage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='timestamp',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
