# Generated by Django 4.2.4 on 2023-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_uploadedimage_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='register_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
